services:
  sepal-gee-bundle:
    build:
      dockerfile: ./Dockerfile
      args:
        HOST_UID: "${HOST_UID:-1000}"
        HOST_GID: "${HOST_GID:-1000}"
    image: "sepal-gee-bundle"
    container_name: sepal-gee-bundle
    volumes:
      - "${EE_CREDENTIALS_PATH:-${HOME}/.config/earthengine/credentials}:/home/mambauser/.config/earthengine/credentials:ro"
    environment:
      SEPAL_HOST: "${SEPAL_HOST:-}"
      FORWARDED_ALLOW_IPS: "*"
      SOLARA_THEME_SHOW_BANNER: "False"
      SOLARA_TEST: "${SOLARA_TEST:-false}"
      LOCAL_SEPAL_USER: "${LOCAL_SEPAL_USER:-}"
      LOCAL_SEPAL_PASSWORD: "${LOCAL_SEPAL_PASSWORD:-}"
      MPLCONFIGDIR: "/tmp/matplotlib"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8768"]
      timeout: 60s
      interval: 1s
      retries: 60
    networks:
      - sepal
    restart: always
    labels:
      org.opencontainers.image.source: https://github.com/sepal-contrib/sepal-gee-bundle

networks:
  sepal:
    external: true
