[supervisord]
user=root
nodaemon=true
loglevel=info

[unix_http_server]
file=/tmp/supervisor.sock
chmod=0777

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:solara]
command=bash -c "micromamba run -n sepal-gee-bundle solara run app.py --host=0.0.0.0 --root-path=/api/app-launcher/sepal-gee-bundle --production --port=8765"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
